import React from 'react';
import { Link } from 'react-router-dom';
import heroFoodImg from '../assets/photo-1512621776951-a57141f2eefd.avif';

const Landing = () => {
  return (
    <div className="flex-grow flex flex-col items-center">
      {/* Hero Section */}
      <section className="w-full relative overflow-hidden bg-slate-50 pt-20 pb-32">
        <div className="absolute top-0 inset-x-0 h-40 bg-gradient-to-b from-orange-50 to-transparent"></div>
        <div className="absolute -top-24 -right-24 w-96 h-96 bg-orange-200 rounded-full mix-blend-multiply filter blur-3xl opacity-70 animate-blob"></div>
        <div className="absolute top-12 -left-24 w-72 h-72 bg-orange-300 rounded-full mix-blend-multiply filter blur-3xl opacity-70 animate-blob animation-delay-2000"></div>
        
        <div className="max-w-7xl mx-auto px-6 relative z-10 text-center">
          <div className="inline-flex items-center gap-2 px-3 py-1 rounded-full bg-orange-100/80 text-orange-600 text-sm font-medium mb-8 border border-orange-200/50 backdrop-blur-sm shadow-sm">
            <span className="relative flex h-2 w-2">
              <span className="animate-ping absolute inline-flex h-full w-full rounded-full bg-orange-400 opacity-75"></span>
              <span className="relative inline-flex rounded-full h-2 w-2 bg-orange-500"></span>
            </span>
            Meet your new AI nutritionist
          </div>
          
          <h1 className="text-5xl md:text-7xl font-bold tracking-tight text-slate-900 mb-6 leading-tight">
            AI Powered <br className="hidden md:block" />
            <span className="text-transparent bg-clip-text bg-gradient-to-r from-orange-600 to-orange-400">Diet Planner</span>
          </h1>
          
          <p className="mt-4 text-xl text-slate-600 max-w-2xl mx-auto mb-10 leading-relaxed">
            Stop guessing what to eat. Get a highly personalized, science-backed diet plan 
            instantly generated by advanced AI based on your unique body goals.
          </p>
          
          <div className="flex flex-col sm:flex-row items-center justify-center gap-4 mb-16">
            <Link 
              to="/register" 
              className="w-full sm:w-auto px-8 py-4 bg-gradient-to-r from-orange-500 to-orange-600 text-white rounded-2xl font-semibold text-lg shadow-lg shadow-orange-500/30 hover:shadow-orange-500/50 hover:-translate-y-1 transition-all duration-300 flex items-center justify-center gap-2"
            >
              Start for free
              <i className="fa-solid fa-arrow-right"></i>
            </Link>
            <Link 
              to="/login" 
              className="w-full sm:w-auto px-8 py-4 bg-white text-slate-700 border border-slate-200 rounded-2xl font-semibold text-lg hover:bg-slate-50 hover:-translate-y-1 transition-all duration-300 shadow-sm"
            >
              Sign in
            </Link>
          </div>

          {/* Hero Image */}
          <div className="max-w-3xl mx-auto relative">
            <div className="absolute -inset-4 bg-gradient-to-r from-orange-400 via-orange-300 to-orange-500 rounded-[2rem] blur-2xl opacity-20 animate-pulse"></div>
            <div className="relative rounded-3xl overflow-hidden shadow-2xl shadow-slate-900/20 border border-white/50 ring-1 ring-slate-200/50">
              <img 
                src={heroFoodImg} 
                alt="Fresh healthy food bowls with colorful vegetables and superfoods" 
                className="w-full h-auto object-cover"
              />
              <div className="absolute inset-0 bg-gradient-to-t from-slate-900/30 via-transparent to-transparent"></div>
              <div className="absolute bottom-4 left-4 right-4 flex items-center justify-between">
                <div className="flex items-center gap-2 px-4 py-2 bg-white/90 backdrop-blur-md rounded-xl shadow-lg">
                  <i className="fa-solid fa-leaf text-orange-500"></i>
                  <span className="text-sm font-semibold text-slate-800">Eat fresh, live healthy</span>
                </div>
                <div className="flex gap-2">
                  <div className="px-3 py-2 bg-white/90 backdrop-blur-md rounded-xl shadow-lg text-xs font-bold text-emerald-600">
                    <i className="fa-solid fa-check mr-1"></i>AI Verified
                  </div>
                </div>
              </div>
            </div>
          </div>
        </div>
      </section>

      {/* Features Section */}
      <section className="w-full py-24 bg-white">
        <div className="max-w-7xl mx-auto px-6">
          <div className="text-center mb-16">
            <h2 className="text-3xl font-bold text-slate-900 mb-4">Everything you need to succeed</h2>
            <p className="text-lg text-slate-600">The most powerful tools to manage your nutrition.</p>
          </div>
          
          <div className="grid md:grid-cols-3 gap-8">
            {/* Feature 1 */}
            <div className="p-8 rounded-3xl bg-slate-50 border border-slate-100 hover:border-orange-200 hover:shadow-xl hover:shadow-orange-500/5 transition-all duration-300 group">
              <div className="w-14 h-14 bg-white rounded-2xl flex items-center justify-center text-orange-500 text-2xl mb-6 shadow-sm group-hover:scale-110 group-hover:bg-orange-500 group-hover:text-white transition-all duration-300">
                <i className="fa-solid fa-wand-magic-sparkles"></i>
              </div>
              <h3 className="text-xl font-bold text-slate-900 mb-3">AI Diet Generation</h3>
              <p className="text-slate-600 leading-relaxed">
                Input your metrics, goals, and dietary preferences. Our AI analyzes millions of data points to generate your perfect meal plan.
              </p>
            </div>
            
            {/* Feature 2 */}
            <div className="p-8 rounded-3xl bg-slate-50 border border-slate-100 hover:border-orange-200 hover:shadow-xl hover:shadow-orange-500/5 transition-all duration-300 group">
              <div className="w-14 h-14 bg-white rounded-2xl flex items-center justify-center text-orange-500 text-2xl mb-6 shadow-sm group-hover:scale-110 group-hover:bg-orange-500 group-hover:text-white transition-all duration-300">
                <i className="fa-solid fa-robot"></i>
              </div>
              <h3 className="text-xl font-bold text-slate-900 mb-3">24/7 AI Chatbot</h3>
              <p className="text-slate-600 leading-relaxed">
                Have questions about a meal? Need to swap an ingredient? Chat with our intelligent assistant anytime for instant nutrition advice.
              </p>
            </div>
            
            {/* Feature 3 */}
            <div className="p-8 rounded-3xl bg-slate-50 border border-slate-100 hover:border-orange-200 hover:shadow-xl hover:shadow-orange-500/5 transition-all duration-300 group">
              <div className="w-14 h-14 bg-white rounded-2xl flex items-center justify-center text-orange-500 text-2xl mb-6 shadow-sm group-hover:scale-110 group-hover:bg-orange-500 group-hover:text-white transition-all duration-300">
                <i className="fa-solid fa-chart-pie"></i>
              </div>
              <h3 className="text-xl font-bold text-slate-900 mb-3">Goal Tracking</h3>
              <p className="text-slate-600 leading-relaxed">
                Stay on track with our comprehensive dashboard. Monitor your macro breakdown, caloric intake, and progress towards your goals.
              </p>
            </div>
          </div>
        </div>
      </section>

      {/* Footer */}
      <footer className="w-full bg-slate-900 py-12 px-6 mt-auto">
        <div className="max-w-7xl mx-auto flex flex-col md:flex-row items-center justify-between gap-6">
          <div className="flex items-center gap-2">
            <div className="bg-orange-500 text-white p-1.5 rounded-lg">
              <i className="fa-solid fa-leaf text-sm"></i>
            </div>
            <span className="text-xl font-bold text-white">NutriAI</span>
          </div>
          <p className="text-slate-400 text-sm">
            © {new Date().getFullYear()} NutriAI. All rights reserved.
          </p>
          <div className="flex gap-4">
            <a href="#" className="w-10 h-10 rounded-full bg-slate-800 flex items-center justify-center text-slate-400 hover:bg-orange-500 hover:text-white transition-colors">
              <i className="fa-brands fa-twitter"></i>
            </a>
            <a href="#" className="w-10 h-10 rounded-full bg-slate-800 flex items-center justify-center text-slate-400 hover:bg-orange-500 hover:text-white transition-colors">
              <i className="fa-brands fa-github"></i>
            </a>
            <a href="#" className="w-10 h-10 rounded-full bg-slate-800 flex items-center justify-center text-slate-400 hover:bg-orange-500 hover:text-white transition-colors">
              <i className="fa-brands fa-linkedin"></i>
            </a>
          </div>
        </div>
      </footer>
    </div>
  );
};

export default Landing;
